### ISSUE TITLE
Datasets with high resolution

### ISSUE THREAD

**Issue by zzgg1** [lzqsd/InverseRenderingOfIndoorScene#6]
Hi! Have you tried the training with higher resolutin like 720*1080? I saw you mentioned networks can generate smoother results with smaller resolution, and if the result will deteriorate a lot with high resolution?

**Comment by lzqsd** [comment]
Hi zzgg1,

We did not exactly try to train with higher resolution images for this project. Because rendering higher resolution data is very time-consuming. But we tried to do that in our prior projects for single object and planar surface BRDF estimation and that's what we observed there. We also observe that compared to 480x640, the results from 240x320 are smoother.
